Modifying Regex for fixing redirection not working when visitin s3-datasets
data-dot-all/dataall pull request #1494
Opened 2024-08-20 23:26 UTC by TejasRGitHub

### Feature or Bugfix
- Bugfix

### Detail

After changes in the names of the URL link to /s3-datasets from /datasets, the redirection is not working when the user logs into data.all with an initial link pointing to the s3-dataset. 

### Relates
- 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-22 11:59 UTC, SofiaSazonova commented
This change didn't work for me
My actions
1. Open new browser window (Firefox, Chrome)
2. Paste the link
I'm redirected to Log in page
3. Log in
I'm redirected to root page, not the target one

2024-08-22 12:00 UTC, SofiaSazonova requested changes
Please check again, or tell me what am I doing wrong

2024-08-22 14:39 UTC, TejasRGitHub commented
Hi @SofiaSazonova , can you please try deploying this code change to one of aws data.all deployments. Can you check if that works ?

2024-08-26 19:41 UTC, TejasRGitHub commented
Removed last commit, since it doesn't work in aws deployed data.all

2024-08-27 07:35 UTC, SofiaSazonova commented
@TejasRGitHub so, what's the verdict? How should we test it?

2024-08-27 13:49 UTC, TejasRGitHub commented
Hi @SofiaSazonova , sorry for the back and forth. Can you test it on your aws deployed ( cognito as authentication ) data.all

2024-08-27 14:55 UTC, SofiaSazonova approved these changes

2024-08-27 14:55 UTC, merged