[Bugfix] - Changes in logic to delete share db
data-dot-all/dataall pull request #1706
Opened 2024-11-19 21:25 UTC by TejasRGitHub

### Feature or Bugfix
- Bugfix

### Detail

- Additional locking when revoking a dataset with the same database shared across various datasets
- Modifications in checks to see if the principal / database combo is still shared else where 

### Relates
- [<URL or Ticket>](https://github.com/data-dot-all/dataall/issues/1633)

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)? N/A
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume? N/A
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization? N/A
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features? N/A
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?  N/A
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-19 22:19 UTC, TejasRGitHub commented
Test cases:

Onboarded two dataset ( D1, D2 ) with the same common_db. Onboarded a consumption role ( C1 ). Environment has two roles ( Scientist, Engineers ) 

Scenerio 1:
1. Created a share S1 with table from C1 to D1 ✅  ( Checked if the tables are accessible via Athena ) 
2. Created a share S2 with table from C1 to D2 ✅  ( Checked if the tables are accessible via Athena ) 
3. Revoked share S2 and checked if the common_db_shared still exists in the account ✅ 
4. Queried tables from S1 to validate access and also checked if LF permissions for the principal exists ✅ 

Scenario 2:
1. Repeated steps 1 and 2. 
2. Created another share S3 with D1 from environment role : Scientist 
3. Checked if access to the table exists for this role ✅ 
4. Now revoked S1 and check if the access in S3 and S2 are intact ✅  ( Checked that the permission to the principals exists and Athena query works) 
5. Revoked S3 and checked if the access to S2 is present ✅  ( Checked that the permission to the principals exists and Athena query works) 
6. Revoked S2 and checked now that the shared database is deleted ✅ 

**TODO** 
Scenario 3:
1. Repeat steps 1 and 2, 
2. Onboard another dataset (D3) in another enviironment where the database name is the same i.e. common_db
3. Now make a share S1 from C1 to this dataset ( D3 )  and also make a share S2 with D2 or D1
4. Revoke share items in share S2 and check if the common_shared db is still present.

2025-01-29 09:44 UTC, dlpzx commented on backend/dataall/modules/s3_datasets/db/dataset_repositories.py
> +            .filter(and_(S3Dataset.deleted.is_(None), S3Dataset.GlueDatabaseName == s3_dataset.GlueDatabaseName))
As you pointed out in your testing scenario 3, there might be issues when 2 datasets from different environments share the same glue database name

2025-01-29 09:51 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +    def list_dataset_shares_on_database(
item_type is defined in the 2 places where this function is called, we can make it a mandatory parameter and avoid the `if item_type: ...` block filtering in the main query.

2025-01-29 09:53 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +        session, dataset_uri, share_item_shared_states, environment_uri=None, item_type=None, database=None
Similarly, environment_uri is not used. As you pointed out in the testing scenario 3, if  we create another dataset in a different environment with the same Glue database name, it will incorrectly list it here. One way to fix this is by passing the environment_uri as a mandatory parameter and use it in the filtering

2025-01-29 10:04 UTC, dlpzx commented on backend/dataall/modules/shares_base/services/sharing_service.py
The `shares_base` module does not depend on `S3_datasets`; shares_base is a generic sharing module that handles the sharing workflow and should not include specific sharing details of a particular sharing_item_type. That means that the logic here that refers to the S3 datasets as well as in `backend/dataall/modules/shares_base/db/share_object_repositories.py` cannot be in shares_base. Instead it needs to be defined in s3_datasets_shares

2025-01-29 10:05 UTC, dlpzx requested changes
The changes requested in https://github.com/data-dot-all/dataall/pull/1706/files#r1933588925 need to be fixed. I have not completed the full review because those changes might impact the whole implementation

2025-01-29 20:21 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +    def list_dataset_shares_on_database(
Okay. That makes sense. I have made changes in the next PR update

2025-01-29 20:28 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +        session, dataset_uri, share_item_shared_states, environment_uri=None, item_type=None, database=None
If we use the environment_uri in the function then will incorrectly be listed out. 

If the same glue db name is used in different environment . Lets say env1 has glue db - db1. Also the same name of glue db name ( db1 ) is used in env2. 
Now a share is made from env3 to env1 and the common shared db is - db1_shared. If env3 makes a share with en2 then the same shared db ( db_shared) will be used. 

Now, when env3 revokes the share it made with env2, for env2 this is the share it made with env3 with the common db (db_shared) but env3 has a share with env1 with common db ( db_shared in env3). Thus, while revoking ( en3 -> env2 share ) the common db should not be removed. 

This function will return the share (env3 -> env1 ) in this case and will prevent cleaning of the shared db

Thinking now, I think the environment_uri filter should be removed, What are you thoughts ?

2025-01-29 21:05 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +
The same argument like the previous function. 

Consider the following diagram , 
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/7476555b-a649-4367-8ddb-c946e7af5141" />


If share 1 is revoked, and if this function `get_shares_for_principal_and_database` filters on source environment URI then in that case it would revoke P1's ( principal 1 ) permission to the shared db even when the same db is used for share 2. 

Due to this reason, I didn't have environment_uri as a filter. 

I am happy to brainstorm any other cases in which the p1 principal will have more permissions when it shouldn't have

2025-01-29 22:07 UTC, TejasRGitHub commented on backend/api_handler.py
ruff reformatting. Please ignore file

2025-01-29 22:07 UTC, TejasRGitHub commented on backend/cdkproxymain.py
> +logger.warning(f'Application started for envname= `{ENVNAME}` DH_DOCKER_VERSION:{os.environ.get("DH_DOCKER_VERSION")}')
ruff reformatting. Please ignore file

2025-01-29 22:07 UTC, TejasRGitHub commented on backend/dataall/base/api/gql/graphql_directive.py
> +                f'@{self.name}({",".join([k + ":" + DirectiveArgs.to_string(self.args[k]) for k in self.args.keys()])})'
ruff reformatting. Please ignore file

2025-01-29 22:08 UTC, TejasRGitHub commented on backend/dataall/base/api/gql/graphql_input.py
> +        args = f'{", ".join([arg.gql() for arg in self.arguments])}'
ruff reformatting. Please ignore file

2025-01-29 22:09 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets/db/dataset_repositories.py
> +            dataset.IAMDatasetAdminRoleArn = f'arn:aws:iam::{dataset.AwsAccountId}:role/{data["adminRoleName"]}'
ruff reformatting. Please ignore file

2025-01-29 22:09 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets/db/dataset_repositories.py
> +    @staticmethod
This file is a part of this PR

2025-01-29 22:10 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets_shares/db/s3_share_object_repositories.py
>      @staticmethod
This file is a part of the PR

2025-01-29 22:10 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets_shares/db/s3_share_object_repositories.py
> +        if environment_uri:
@dlpzx , please let me know if you agree on removing the environment_uri filter

2025-01-29 22:11 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets_shares/services/share_processors/glue_table_share_processor.py
> +        # Find out all the datasets where the same db is used and lock all those datasets
This file is a part of this PR

2025-01-29 22:11 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets_shares/services/share_processors/glue_table_share_processor.py
> +        # Find out all the datasets where the same db is used and lock all those datasets
Changes are from L232 to L262 . Rest of the code inside the `with` block is the same.

2025-01-29 22:13 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/services/sharing_service.py
> +        status_list = [status] if status is not None else []
This is a simplification and correction. The earlier logic was buggy and use to give incorrect result as [None] was passed.

2025-01-29 22:15 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/services/sharing_service.py
Hey @dlpzx , sorry for this. I have now moved the entire section corresponding to S3 dataset to the glue_table_processor implementation. Please let me know if it looks good. 
I will perform a round of testing after these changes and let u know accordingly

2025-01-29 22:17 UTC, TejasRGitHub commented
> The changes requested in https://github.com/data-dot-all/dataall/pull/1706/files#r1933588925 need to be fixed. I have not completed the full review because those changes might impact the whole implementation

@dlpzx , I have made changes to fix the structure of the code. 

There are lot of file which have changed when I did `make lint` with the newer version of ruff due to which you are seeing a lot of file which are updated. I have marked the files which are a part of this PR to make it easy to review PR

2025-01-30 08:35 UTC, dlpzx commented on backend/dataall/modules/shares_base/services/sharing_service.py
> +    ShareableType,
This import is no longer used

2025-01-30 08:37 UTC, dlpzx commented on backend/dataall/modules/shares_base/services/sharing_service.py
> +        status_list = [status] if status is not None else []
Thanks I see it!

2025-01-30 08:39 UTC, dlpzx commented on backend/dataall/modules/s3_datasets_shares/services/share_processors/glue_table_share_processor.py
> +from dataall.modules.s3_datasets.api.dataset.types import Dataset
```from dataall.modules.datasets_base.db.dataset_models import DatasetBase
from dataall.modules.datasets_base.db.dataset_repositories import DatasetBaseRepository
from dataall.modules.s3_datasets.api.dataset.types import Dataset```

Those 3 lines are unused imports

2025-01-30 08:45 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +
I forgot about the common name! it is true that db_shared can be used for multiple dbs from different accounts. I think you are right!

2025-01-30 08:46 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +        session, dataset_uri, share_item_shared_states, environment_uri=None, item_type=None, database=None
I commented below, you are right, even from different environments the shared db does not contain any unique identifier. The same shared_db is used for both environments. Thanks for the diagram, I realized in a minute!

2025-01-30 08:47 UTC, dlpzx commented on backend/dataall/modules/shares_base/services/sharing_service.py
> +    ShareableType,
And this block neither:
```
rom dataall.modules.datasets_base.db.dataset_repositories import DatasetBaseRepository
from dataall.modules.s3_datasets.db.dataset_models import S3Dataset
from dataall.modules.s3_datasets.db.dataset_repositories import DatasetRepository
from dataall.modules.datasets_base.db.dataset_models import DatasetBase
```
This one we need to remove to avoid potential circular dependencies

2025-01-30 08:52 UTC, dlpzx requested changes
Only some imports need to be removed. The rest looks good IMO. 
I am testing the ruff changes in a separate PR. There are format changes that require testing

2025-01-30 17:29 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/services/sharing_service.py
> +    ShareableType,
Updated in the next PR

2025-01-30 17:30 UTC, TejasRGitHub commented
> Only some imports need to be removed. The rest looks good IMO. I am testing the ruff changes in a separate PR. There are format changes that require testing

Thanks @dlpzx , removed unused imports and also synced PR branch with. the main. now the ruff formatting changes should not appear.

2025-01-31 13:56 UTC, dlpzx commented on backend/dataall/modules/s3_datasets_shares/db/s3_share_object_repositories.py
> +        if environment_uri:
Agree!

2025-01-31 16:32 UTC, TejasRGitHub commented
@dlpzx , I ran make lint and also unit test and everythings passed on my end. Acc to me, I think now this PR is also ready to be merged

2025-02-03 10:52 UTC, dlpzx commented on backend/dataall/modules/s3_datasets_shares/db/s3_share_object_repositories.py
> +    ) -> [ShareObject]:
the input parameter `database` is always included in the call and it is needed in the filter, it should not default to None, it should just be mandatory

2025-02-03 10:58 UTC, dlpzx requested changes
Left one minor comment, the rest looks good~

2025-02-03 18:10 UTC, TejasRGitHub commented on backend/dataall/modules/s3_datasets_shares/db/s3_share_object_repositories.py
> +    ) -> [ShareObject]:
Sure. Damm I missed this.

2025-02-03 18:13 UTC, TejasRGitHub commented
> Left one minor comment, the rest looks good~

@dlpzx , Updated PR with correction

2025-02-04 07:17 UTC, dlpzx approved these changes

2025-02-04 10:33 UTC, SofiaSazonova approved these changes

2025-02-04 11:17 UTC, merged