Metadata form enforcement
data-dot-all/dataall pull request #1730
Opened 2024-12-04 13:56 UTC by SofiaSazonova

### Feature or Bugfix

- Feature

### Detail
**MF view**
1. Enforcement rule tab is added
2. MF owner can add Enforcement rules, others can view
3. For each Enforcement rule user can see entities affected by it and if the form is attached or not
4. Rule is automatically updated for latest MF versions when version is created/deleted

**Entity view**
1. If any enforced forms are missing from entity 'Metadata' tab on it's page has "alarm" icon
2. Missing MFs are highlighted  in the list of attached entities

**Backend**
1. New core component MetadataFormEntityManager. 
2. All eligible entities register in this manager, when their module is enabled
3. This manager is unused if metadata form module is not created
4. Metadata form module depends on DatasetBase module, because we have 'Dataset' enforcement level and logic binded to it.

**IMPORTANT**
Before this PR is merged, I will deregister modules, which don't have frontend for MF yet.

### Relates
- #1668 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-05 21:22 UTC, SofiaSazonova commented
https://github.com/user-attachments/assets/c989d438-0c6c-4bba-add6-e79c46eabcc1

2025-01-31 15:16 UTC, petrkalos requested changes
* there are some major architectural issues that we agreed to rectify at a later PR, I tried to write a detailed comment to convert directly to an issue in our backlog
* there are some that are bit more minor but I think they must be addressed (easy wins here and tehre)
* you will have to rebase and fix the persmission tests

2025-01-31 15:16 UTC, petrkalos commented on backend/dataall/modules/metadata_forms/services/metadata_form_enforcement_service.py
> +            session.commit()
this logic belongs to the repo, also first `get` then `delete` suboptimal, perhaps there is a native way to do it something like `session.query(MetadataFormEnforcementRule).filter_by(id=rule_uri).delete()`

2025-02-03 11:24 UTC, dlpzx commented on frontend/src/modules/Organizations/views/OrganizationView.js
>  import { isModuleEnabled, ModuleNames } from '../../../utils';
nit: utils is a global package, we should use global imports; I think in general we should review UI imports in the metadata forms module

2025-02-07 13:55 UTC, SofiaSazonova commented on backend/dataall/modules/metadata_forms/api/resolvers.py
I follow the notation in other resolvers 
e.g. `s3_dataset/dataset/resolvers`,  `share_base/api/resolvers` ...

2025-02-07 13:57 UTC, SofiaSazonova commented on backend/dataall/modules/metadata_forms/db/metadata_form_repository.py
> +    def update_version_in_rules(session, uri, version):
It's not rule version. It version of MF that is used in rule

2025-02-10 10:31 UTC, dlpzx commented on backend/dataall/core/environment/db/environment_models.py
> +    __metaclass__ = MetadataFormEntity
+1 on using inheritance on the Resource ABC class

2025-02-10 13:59 UTC, SofiaSazonova commented on backend/dataall/modules/metadata_forms/services/metadata_form_enforcement_service.py
> +                return OrganizationRepository.query_organization_environments(session, uri=rule.homeEntity, filter=None)
done

2025-02-10 13:59 UTC, SofiaSazonova commented on frontend/src/modules/Organizations/views/OrganizationView.js
>  import { isModuleEnabled, ModuleNames } from '../../../utils';
done

2025-02-10 14:00 UTC, SofiaSazonova commented on backend/dataall/core/organizations/db/organization_models.py
> +MetadataFormEntityManager.register(OrganizationGroup, MetadataFormEntityTypes.OrganizationTeams.value)
It's related to what we show to user.
If you insist on using model.name, we will anyway have to map it to user-readable names.

2025-02-11 08:32 UTC, dlpzx commented on backend/dataall/modules/dashboards/db/dashboard_models.py
>          return cls.dashboardUri
the `get_uri` function is missing, is it because `uri` is used instead?

2025-02-11 08:35 UTC, dlpzx commented on backend/dataall/core/organizations/db/organization_repositories.py
> +
very nit: instead of returning the Query object, which is a very sqlalchemy-specific class, we could return directly the list of organizations and not call `.all()` in the metadata form service

2025-02-11 08:39 UTC, dlpzx commented on backend/dataall/core/metadata_manager/metadata_form_entity_manager.py
> +    MLStudioEntities = 'ML Studio Entity'
nit: rename `MLStudioEntities` to `MLStudioUser`
nit2: some names are in plural, other in singular

2025-02-11 08:53 UTC, dlpzx commented on backend/dataall/core/metadata_manager/metadata_form_entity_manager.py
> +
instead of registering the resources with a [str, MetadataFormEntity] you could use the enum `MetadataFormEntityTypes` to ensure only those are registered

2025-02-11 09:10 UTC, dlpzx commented on frontend/src/modules/Organizations/views/OrganizationView.js
> +import { listRulesThatAffectEntity } from '../../Metadata_Forms/services';
Alongside the whole PR and the implementation of the UI components of metadata forms there are violations of the modularization principles established in data.all v2.

The idea is that any of the FE modules can be replaced or removed without affecting other modules. Anything that is shared across modules is placed in the global packages. That means that imports such as `'../../Metadata_Forms/services';` that go 2 levels up and get an API from another module are "forbidden" because if we were now to remove or alter the Organizations module other modules would be affected. 

The whole MF module needs to be reviewed, but I think this task can be left out of this PR.

2025-02-11 09:19 UTC, dlpzx commented on frontend/src/modules/Metadata_Forms/components/MetadataFormEnforcement.js
> +      await fetchDatasets();
I am not sure of this, but can we restrict the fetchX call to call only the one of the enforcementScope selected? If we are using the Organizations, we do not need to fetch Environments and Datasets and we can save 2 costly API calls

2025-02-11 09:32 UTC, dlpzx approved these changes
Left some comments, mostly minor

2025-02-12 09:04 UTC, petrkalos commented on backend/dataall/modules/metadata_forms/services/metadata_form_enforcement_service.py
>                  rule = MetadataFormRepository.get_mf_enforcement_rule_by_uri(session, uri)
is this change of indentation intentional?
previously if rule!=None you will run the logic of your function
now if rule!=None you will skip it

2025-02-12 09:05 UTC, petrkalos requested changes
making sure that the change in `get_affected_environments` logic is intented

2025-02-12 10:15 UTC, SofiaSazonova commented on backend/dataall/modules/metadata_forms/services/metadata_form_enforcement_service.py
>                  rule = MetadataFormRepository.get_mf_enforcement_rule_by_uri(session, uri)
You are right!

2025-02-12 11:01 UTC, SofiaSazonova commented on backend/dataall/core/environment/db/environment_models.py
> +    __metaclass__ = MetadataFormEntity
separarte issue opened

2025-02-12 11:01 UTC, SofiaSazonova commented on backend/dataall/modules/dashboards/db/dashboard_models.py
>          return cls.dashboardUri
done

2025-02-12 11:29 UTC, SofiaSazonova commented on backend/dataall/core/metadata_manager/metadata_form_entity_manager.py
> +
Let's do in in backend refactoring, when rewriting EntityManager

2025-02-12 11:31 UTC, SofiaSazonova commented on backend/dataall/modules/metadata_forms/api/resolvers.py
It's main resolver
getMetadataForm = gql.QueryField(
    name='getMetadataForm',
    args=[gql.Argument('uri', gql.NonNullableType(gql.String))],
    type=gql.Ref('MetadataForm'),
    resolver=get_metadata_form,
    test_scope='MetadataForm',
)

subquery has different source

2025-02-12 13:39 UTC, petrkalos approved these changes

2025-02-12 15:42 UTC, merged