[BUGFIX] gh-1734
data-dot-all/dataall pull request #1741
Opened 2024-12-12 15:59 UTC by TejasRGitHub

### Feature or Bugfix
- Bugfix

### Detail

- After tables are synced and if the tables are deleted from the glue db then delete the tables where they are used in the shares and add an activity records for it

### Relates
- https://github.com/data-dot-all/dataall/issues/1734

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2025-01-29 10:17 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
get_shares_for_principal_and_database should not be part of this PR

2025-01-29 10:24 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +            query = query.filter(share_type_model.LastGlueTableStatus == 'InSync')
We could consider that this is glue-specific logic; but since we are using the share_type_model and the ShareableType objects I think this can be an exception. Good to go

2025-01-29 10:25 UTC, dlpzx requested changes
If we remove `get_shares_for_principal_and_database` from this PR it is good to go

2025-01-29 17:09 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +            query = query.filter(share_type_model.LastGlueTableStatus == 'InSync')
yeah right now the share_type_model for table is only for glue. In the future, it would be great to decouple this such that it is any table ( i.e. glue, bigquery from gcp or anyother type )

2025-01-29 17:15 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
Oh yes. I will remove this. Yeah I will also take care of this in the PR it was introduced .

2025-01-29 17:15 UTC, TejasRGitHub commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
Thanks for spotting this @dlpzx

2025-01-29 17:17 UTC, TejasRGitHub commented
> If we remove `get_shares_for_principal_and_database` from this PR it is good to go

Updated PR

2025-01-30 08:28 UTC, dlpzx commented on backend/dataall/modules/shares_base/db/share_object_repositories.py
> +from dataall.modules.s3_datasets.db.dataset_models import S3Dataset
Can you also remove the import to S3Dataset? It is not used and it imports parts of s3_datasets, with the potential risk of circular dependencies

2025-01-31 14:41 UTC, dlpzx approved these changes

2025-01-31 14:43 UTC, petrkalos approved these changes

2025-02-03 07:22 UTC, merged